{
  name = "saxpy-cuda-test";

  containers.container =
    { pkgs, ... }:
    {
      environment.systemPackages = [
        pkgs.cudaPackages.saxpy
      ];

      # Misc cuda mounts.
      # This was generated by running:
      #   nix run nixpkgs#nix-required-mounts $(nix-instantiate -E 'derivation {name = "needs-cuda"; builder = "-"; system = "-"; requiredSystemFeatures = ["cuda"]; }') | grep -v '^/nix/store'warning
      virtualisation.systemd-nspawn.options = [
        "--bind=/host/run/opengl-driver:/run/opengl-driver"
        "--bind=/dev/dri:/dev/dri"

        # on AMD/NVIDIA, there's more paths.
        # see also cuda-in-container-nvidia/amd.nix
      ];
    };

  testScript = /* python */ ''
    container.start()

    output = container.succeed("saxpy 2>&1")
    assert "Max error: 0.000000" in output

    print("CUDA output:")
    print(output)
  '';
}
